---
title: "data analysis"
author: "Chrissy & Ricky"
date: '`r Sys.Date()`'
output: html_document
---

```{r load-packages, message = FALSE}
library(tidyverse) ## For plotting and data wrangling.
library(readr)
library(broom)
library(fivethirtyeight)
library(WDI)
library(rgdal)
library(leaflet) ## For leaflet interactive maps
library(sf) ## For spatial data
library(RColorBrewer) ## For colour palettes
library(htmltools) ## For html
library(leafsync) ## For placing plots side by side
library(kableExtra) ## Table  output (in slides)
```

```{r heat-map-package}
library(ggplot2)
library(dplyr) # easier data wrangling 
library(viridis) # colour blind friendly palette, works in B&W also
#library(Interpol.T) #  will generate a large dataset on initial load
library(lubridate) # for easy date manipulation
library(ggExtra) # because remembering ggplot theme options is beyond me
library(tidyr) 
```


```{r import_data}
covid_data <- readr::read_csv(file = "../data/owid-covid-data.csv")
covid_data_codebook <- readr::read_csv(file = "../data/owid-covid-codebook.csv")
```


## Data Cleaning and Manipulation

The data is from 2020-02-24 to 2022-02-24
```{r data-cleaning, include=FALSE}
covid_total <- covid_data %>%
  filter(date == "2022-02-24")

covid_country <- covid_total %>%
  filter(is.na(continent) == FALSE)

covid_other <- covid_total %>%
  filter(is.na(continent) == TRUE)
```

```{r}
covid_total <- covid_data %>%
  filter(date == "2021-02-24")

covid_country <- covid_total %>%
  filter(is.na(continent) == FALSE)

covid_other <- covid_total %>%
  filter(is.na(continent) == TRUE)
```


```{r parse-date}
dates <- as.POSIXct(covid_country, format = "%Y/%m/%d")
format(dates, format="%Y")
```

## Maps


# [1a] summary statistics

```{r cases-map, echo = FALSE}
cases <- covid_data %>%
  filter(date == "2022-02-18") %>%
  filter(is.na(continent) == FALSE) %>%
  select(iso_code, location, date, total_cases_per_million) %>%
  na.omit()

world_spdf <- readOGR( 
  dsn= ("/cloud/project/data/world_shape_file/"), 
  layer="TM_WORLD_BORDERS-0.3",
  verbose=FALSE)

world_spdf2 <- st_read("/cloud/project/data/world_shape_file/TM_WORLD_BORDERS-0.3.shp")

cases_map <- cases %>% 
  left_join(world_spdf2, by = c("location" = "NAME")) %>%
  st_as_sf()

pal2 <- colorNumeric(palette = "RdYlGn", domain = cases_map$total_cases_per_million)
labels <- sprintf("<strong>%s</strong><br/>%s ", cases_map$location, cases_map$total_cases_per_million) %>%
  lapply(htmltools::HTML)

c_map <- leaflet(data = cases_map) %>% 
  addTiles()  %>% 
  setView( lat=10, lng=0 , zoom=1) %>%
  addPolygons(fillColor = ~pal2(cases_map$total_cases_per_million),
                                 fillOpacity = 1, 
                                 color = "white",
                                 opacity = 1,
                                 weight = 1,
                                 label = labels) %>%
  addLegend("bottomleft", pal = pal2, values = ~cases_map$total_cases_per_million,
    title = "Total Cases per Million",
    opacity = 1)

c_map
```

---

Medical resources (icu_patients_per_million)
```{r icu, echo = FALSE}
icu_ad <- covid_data %>%
  filter(date == "2022-02-20") %>%
  filter(is.na(continent) == FALSE) %>%
  select(location, icu_patients_per_million) %>%
  arrange(desc(icu_patients_per_million)) %>%
  top_n(10)

icu_ad
```

---

```{r ICU-map, echo = FALSE}
ICU <- covid_data %>%
  filter(date == "2022-01-01") %>%
  filter(is.na(continent) == FALSE) %>%
  select(iso_code, location, date, icu_patients_per_million) %>%
  na.omit()

world_spdf <- readOGR( 
  dsn= ("/cloud/project/data/world_shape_file/"), 
  layer="TM_WORLD_BORDERS-0.3",
  verbose=FALSE)

world_spdf2 <- st_read("/cloud/project/data/world_shape_file/TM_WORLD_BORDERS-0.3.shp")

icu_map <- ICU %>% 
  left_join(world_spdf2, by = c("location" = "NAME")) %>%
  st_as_sf()

pal2 <- colorNumeric(palette = "RdYlGn", domain = icu_map$icu_patients_per_million)
labels <- sprintf("<strong>%s</strong><br/>%s ", icu_map$location, icu_map$icu_patients_per_million) %>%
  lapply(htmltools::HTML)

i_map <- leaflet(data = icu_map) %>% 
  addTiles()  %>% 
  setView( lat=10, lng=0 , zoom=1) %>%
  addPolygons(fillColor = ~pal2(icu_map$icu_patients_per_million),
                                 fillOpacity = 1, 
                                 color = "white",
                                 opacity = 0.7,
                                 weight = 1,
                                 label = labels) %>%
  addLegend("bottomleft", pal = pal2, values = ~icu_map$icu_patients_per_million,
    title = "ICU",
    opacity = 1)

i_map
```


---

# [1a] summary statistics - diabetes
General health information (diabetes prevalence)
```{r diabetes, echo = FALSE}
diab <- covid_data %>%
  filter(date == "2022-02-20") %>%
  filter(is.na(continent) == FALSE) %>%
  mutate(diabetesp = (diabetes_prevalence)/100) %>%
  select(location, diabetesp) %>%
  arrange(desc(diabetesp)) %>%
  top_n(10)

diab$diabetesp <- percent(diab$diabetesp, accuracy=1)
diab
```
---

```{r diab-map, echo = FALSE}
diabetes <- covid_data %>%
  filter(date == "2022-02-20") %>%
  filter(is.na(continent) == FALSE) %>%
  select(iso_code, location, date, diabetes_prevalence) %>%
  na.omit()

world_spdf <- readOGR( 
  dsn= ("/cloud/project/data/world_shape_file/"), 
  layer="TM_WORLD_BORDERS-0.3",
  verbose=FALSE)

world_spdf2 <- st_read("/cloud/project/data/world_shape_file/TM_WORLD_BORDERS-0.3.shp")

diab_map <- diabetes %>% 
  left_join(world_spdf2, by = c("location" = "NAME")) %>%
  st_as_sf()

pal2 <- colorNumeric(palette = "RdYlGn", domain = diab_map$diabetes_prevalence)
labels <- sprintf("<strong>%s</strong><br/>%s ", diab_map$location, diab_map$diabetes_prevalence) %>%
  lapply(htmltools::HTML)

di_map <- leaflet(data = diab_map) %>% 
  addTiles()  %>% 
  setView( lat=10, lng=0 , zoom=1) %>%
  addPolygons(fillColor = ~pal2(diab_map$diabetes_prevalence),
                                 fillOpacity = 1, 
                                 color = "white",
                                 opacity = 0.7,
                                 weight = 1,
                                 label = labels) %>%
  addLegend("bottomleft", pal = pal2, values = ~diab_map$diabetes_prevalence,
    title = "Diabetes Prevalence (%)",
    opacity = 1)

di_map
```




## Heat Map

```{r time-heat-map}
p <-ggplot(covid_country, aes(day,hour,fill=temp))+
  geom_tile(color= "white",size=0.1) + 
  scale_fill_viridis(name="Hrly Temps C",option ="C")
p <-p + facet_grid(year~month)
p <-p + scale_y_continuous(trans = "reverse", breaks = unique(df$hour))
p <-p + scale_x_continuous(breaks =c(1,10,20,31))
p <-p + theme_minimal(base_size = 8)
p <-p + labs(title= paste("Hourly Temps - Station",statno), x="Day", y="Hour Commencing")
p <-p + theme(legend.position = "bottom")+
  theme(plot.title=element_text(size = 14))+
  theme(axis.text.y=element_text(size=6)) +
  theme(strip.background = element_rect(colour="white"))+
  theme(plot.title=element_text(hjust=0))+
  theme(axis.ticks=element_blank())+
  theme(axis.text=element_text(size=7))+
  theme(legend.title=element_text(size=8))+
  theme(legend.text=element_text(size=6))+
  removeGrid()#ggExtra
 
# you will want to expand your plot screen before this bit!
p #awesomeness
```

## Statistical analyses and regressions

```{r linear-models}
linear_reg() %>%
  set_engine("lm") %>%
  fit(total_cases_per_million ~ population_density + hospital_beds_per_thousand, data = covid_country) %>%
  tidy()
```

## More advanced models and machine learning

```{r}

```




